### PR TITLE
Edited movebase.launch to include "with_social_layer" to surport social navigation layers

### PR DESCRIPTION
**Pull request by jmcjacob**
Added the parameter "with_social_layer" that by default is set to false. The new parameters will allow the use of the [Proxemic and Passing layers](https://github.com/DLu/navigation_layers/tree/indigo/social_navigation_layers) to be added to the global costmap.

### CODE REVIEW

**Comment by nilsbore** [comment]
Hi! Is there any reason to add the parameter before the functionality is implemented or could it wait until then?

**Comment by marc-hanheide** [comment]
I suppose this is being implemented in another repo? @cdondrup ? Is this in https://github.com/strands-project/scitos_2d_navigation/pull/59 ?

**Comment by cdondrup** [comment]
The functionality is implemented by someone else but just not a package yet. I asked to open the PRs because if the parameter is just left to its default value, it will not change the current robot behaviour and won't break anything. Therefore once the repo is turned into a package, this will work as intended.

**Comment by nilsbore** [comment]
This PR is very outdated, closing.

**Pull request closed without merging**
