### PR TITLE
[strands_movebase] Don't add obstacles at edge of laser's FOV

### PR DESCRIPTION
**Pull request by nilsbore**
This pull request adds a new node, `remove_edges_laser` that removes a small angle at the beginning and end of the laser scan. This new scan is then used to add obstacles in the costmap while the old, full, scan is used for clearing them. This should solve https://github.com/strands-project/strands_movebase/issues/25 .

Since I am unable to try this out on Rosie atm (going on 48 hours now=P) and we are performing a marathon, I would encourage those that think that this affects the performance of their robot's navigation to try it before we merge. @BFALacerda @lucasb-eyer

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
Will also not try it before the marathon, but hopefully won't forget about it thereafter!

**Comment by bfalacerda** [comment]
Bob is using it

**Comment by nilsbore** [comment]
Bob: King. If there are still lingering obstacles added by the laser, you can increase the `laser_angle_cutoff` parameter.

**Comment by nilsbore** [comment]
@BFALacerda We've tested this on Rosie now also and I can't get obstacles to linger though it wasn't exactly consistent before either. Any objections to merging this?

**Comment by bfalacerda** [comment]
we can merge it, it doesn't hurt. I'm also not 100% sure that it avoids the addition of lingering obstacles, but we had less problems since we added this.

We're also back to  using the costmap reloading recovery behaviour so it's hard to know what improved the performance. Anyway, merging now and will do further testing later

**Comment by lucasb-eyer** [comment]
> I'm also not 100% sure that it avoids the addition of lingering obstacles

I think the current costmap approach of ROS is fundamentally flawed and we'll never completely get rid of lingering points. But this sounds like it will (highly?) reduce their probability.

**Pull request merged**
