### PR TITLE
[strands_movebase] Changed the machine tags

### LINKED ISSUE #56: [strands_movebase] Add machine tag to launch the head camera processing node on right PC
Yeah.

### PR DESCRIPTION
**Pull request by nilsbore**
Changed the machine tags to be able to launch the head camera processing nodes on the correct pc. Waiting for @cdondrup to try this out on Werner. Fixes https://github.com/strands-project/strands_movebase/issues/56

### CODE REVIEW

**Comment by nilsbore** [comment]
@marc-hanheide Me and @cdondrup tested on Werner. It works fine and it's a good thing to do :tm: since it changes the backtrack to do the point cloud processing on the same PC as the head camera is running, saving bandwidth whenever the backtracking kicks in. Ok to merge?

**Comment by cdondrup** [comment]
The machine for the backtracking code defaults to `localhost` so there should be no change to the default behaviour. Maybe someone from b'ham can have a look? @cburbridge @bfalacerda jut to make sure it doesn't break anything for you guys.

**Comment by cdondrup** [comment]
One of the launch files sets the `default` to `true` for the chest machine and therefore all nodes after that launch file has been included are also launched on the chest machine, i.e. human_aware_navigation. This still works but is not how it's intended. Will have to fix.

Who had the brilliant idea to have the machine tag in an included launch file influence the nodes started in the top level launch file??? Damn remote starting mechanisms.

Will fix after pre-deployment.

**Comment by cdondrup** [comment]
This has been tested on henry during the pre-deployment and worked fine. Reduces the load on the main PC and the network.
It does remove the parameters `machine` and `user` from the `obstacle.launch` but does not change the default behaviour. Can this be merged?

Above error has to be fixed in a different launch file.

**Comment by nilsbore** [comment]
I tested this quite extensively on Henry also, I think it can be merged. @marc-hanheide ?

**Pull request merged**
