### PR TITLE
[strands_movebase] Add launch parameters to change obstacle thresholds

### PR DESCRIPTION
**Pull request by nilsbore**
This pull:
- Allows you to specify how high above the ground a point has to be to be counted as an obstacle (as opposed to floor, which is used for ray-tracing to clear obstacles). Via launch parameter `z_obstacle_threshold`.
- Same thing for stair detection, how low below the ground plane to be counted as stairs via the launch parameter `z_stair_threshold`.

This allows you to find a good balance between how sensitive a robot is to obstacles near the floor plane (low obstacles) and how robust the robot is. Our experience is that the navigation can be much more robust by setting e.g. `z_obstacle_threshold:=0.2` and `z_stair_threshold:=0.12`.

### CODE REVIEW

**Comment by nilsbore** [comment]
I must set up git on the robot to not make @RaresAmbrus get any unfair advantage in the commit statistics=P.

**Comment by marc-hanheide** [comment]
if `z_obstacle_threshold:=0.2` and `z_stair_threshold:=0.12` appears to be the best setting why not making it default then?

**Comment by marc-hanheide** [comment]
I see that they are potentially a bit riskier, but I would say they're not more risky than the defaults we have at the moment anyway

**Comment by nilsbore** [comment]
I don't know, I think it's up for discussion. Some people have been concerned about setting these thresholds too high since we might run over something. But I think this should be merged so it's easy to change anyways. If you don't have any stairs in your environment, you might want to set `z_stair_threshold` very high for example.

**Comment by marc-hanheide** [comment]
OK, agreed.

**Pull request merged**
