### PR TITLE
removed strands_navfn

### LINKED ISSUE #73: [strands_navfn] is not melodic-ready
as https://lcas.lincoln.ac.uk/buildfarm/job/Mdev__strands_movebase__ubuntu_bionic_amd64/ shows, `strands_navfn` refuses to compile for ROS melodic.

The problem is a lot of API changes in `move_base`: https://github.com/paulbovbel/frontier_exploration/issues/38#issuecomment-449415389

So, question: What does `strands_navfn` offer that the standard `navfn` doesn't? Can it be removed?

### PR DESCRIPTION
**Pull request by marc-hanheide**
as discussed in #73 

closes #73

### CODE REVIEW

**Comment by bfalacerda** [comment]
should we add a melodic-devel branch rather than merge this into indigo-devel?

**Comment by marc-hanheide** [comment]
> should we add a melodic-devel branch rather than merge this into indigo-devel?

We could... I prefer to have one main branch to avoid extra work... but you may have a point

**Comment by marc-hanheide** [comment]
agreed with @bfalacerda ... closing this and pulling into `melodic-devel` instead: #75

**Comment by bfalacerda** [comment]
I'm happy to have melodic-devel as the main branch, but leaving this one as is just in case

**Pull request closed without merging**
