### PR TITLE
setting unknown_cost_value to 100

### PR DESCRIPTION
**Pull request by Jailander**
solves issue #39

### CODE REVIEW

**Comment by bfalacerda** [comment]
We also have the `allow_unknown` param for the global planner that could be set to false. That solution looks cleaner than this one, have you tried it?

**Comment by Jailander** [comment]
I have done some testing with this and haven't been able to make it plan over unknown areas **yet**, so I guess that works, I'll keep testing.

As for the _allow_unknown_ parameter apparently is the one that actually considers unknown cells in the cost_map as unknown if not it just gives them obstacle cost, but it does seem a bit hacky as seen in https://github.com/ros-planning/navigation/blob/indigo-devel/navfn/src/navfn.cpp#L251

I'll test changing both today and change the pull request if needed, so don't merge just yet

**Comment by marc-hanheide** [comment]
@Jailander said:

> I'll test changing both today and change the pull request if needed, so don't merge just yet

So?

**Comment by Jailander** [comment]
This works and has been tested

**Comment by marc-hanheide** [comment]
how is this related to https://github.com/strands-project/strands_navigation/pull/188?

**Comment by Jailander** [comment]
It isn't, this has been tested and is ready to be merged, why?

**Comment by marc-hanheide** [comment]
sorry... got lost ;-)

**Comment by Jailander** [comment]
Hahaha Ok, me too :-D

**Pull request merged**
