### PR TITLE
[strands_movebase] Decreased the cost_scaling_factor

### PR DESCRIPTION
**Pull request by nilsbore**
This makes the robot stay further away from walls if possible. This made navigation more robust on Rosie, particularly through doors where we had a problem of running into the doorway sometimes.

### CODE REVIEW

**Comment by marc-hanheide** [comment]
I have no idea if this could have any side effects. But if you tested it, I'm inclined to accept it.

**Comment by nilsbore** [comment]
We've been running with this during the whole summer and while it's really hard to know with these things, both me and @RaresAmbrus think that it improves performance.

**Comment by marc-hanheide** [comment]
having just merged this... can you tell me which branch should be the main one? we have master and hydro-devel here, and both have commits to it... Currently, jenkins build `master`, but maybe that's not what you want?

**Comment by nilsbore** [comment]
The hydro-devel branch should be the main one now.

**Comment by nilsbore** [comment]
I didn't see your changes to master but we should probably merge those to hydro-devel then. Thanks for remembering to install the urdf!

**Comment by marc-hanheide** [comment]
please see https://github.com/strands-project/strands_movebase/pull/8 and accept ;-)

**Pull request merged**
