### PR TITLE
[strands_movebase] Add option to use head_camera as well

### PR DESCRIPTION
**Pull request by nilsbore**
This adds the parameter `with_head_camera:=<bool>` to `movebase.launch`. If enabled, it will make the obstacle voxel grid higher to account for the head camera and listen to points on topic `/move_base/head_points_clearing` as published by `backtrack.launch` in `backtrack_behaviour` package. If you want to use the `backtrack_behaviour` recovery behaviour, you have to set `with_head_camera:=true` when launching `movebase.launch`.

This also fixes private namespace parameters for all the nodes in this package since that is needed when using multiple nodes of the same type.

### CODE REVIEW

**Comment by nilsbore** [comment]
@BFALacerda Maybe you can give this a try, it's working fine over here.

**Comment by bfalacerda** [comment]
We're having some issues with our ptu, I can't test the backtrack behaviour until it's fixed: testing this on Monday is not possible, hopefully I can do it no later than Wednesday

**Comment by nilsbore** [comment]
Maybe @Jailander can have a look then. I also have to test this as a recovery behaviour (have checked that the action server is working), haven't gotten the navigation running yet but with @Jailander 's launch file it should be easy.

**Comment by marc-hanheide** [comment]
@Jailander I'll assign this to you as you are mentioned as the one to test ;-) Please comment on it.

**Comment by bfalacerda** [comment]
I'm happy to take this one out of your hands @Jailander , tomorrow I'm going to test monitored_navigation on bob

**Comment by nilsbore** [comment]
I've had some time to try the recovery behaviour here (which is actually already released=P). The backtrack behaviour in general returns success but then navigation can't recover anyways for some reason, seems like it's preempted.

**Comment by bfalacerda** [comment]
if you're using only monitored navigation, that's the new approach: after a failure, it tries to recover and then reports back to topological navigation. It is done like this so that topological navigation can check the new position of the robot and decide what's the navigation action to take next. Before we were having issues with monitored_navigation insisting on door_passing when it was already through the door, for example.

If you're using topological navigation already, then there's some bug I guess

**Comment by marc-hanheide** [comment]
About this PR... Any :+1: for merge?

**Comment by nilsbore** [comment]
I don't see any downsides, it adds the option of a head camera but the default behaviour is still the same. Besides, it's needed for `backtrack_behaviour`.

**Comment by bfalacerda** [comment]
yeah, i forgot about this one... :+1: 

@nilsbore is the issue you reported about mon nav covered in my answer above, or is it something else?

**Comment by nilsbore** [comment]
I was using topological navigation so I think there might be some bug. I'll see if I can give you something more concrete.

**Pull request merged**
